<?php
bolt_decrypt( __FILE__ , 'TkEexH'); return 0;
##!!!##MzOXipaOnJmKjI5JapmZhXaYjY6VnGQzM56cjklylZWelpKXip2OhW2KnYqLipyOhW6VmJqejpedhW+KjJ2Ym5KOnIVxipxvioydmJuiZDOenI5JcpWVnpaSl4qdjoVtip2Ki4qcjoVulZiano6XnYV2mI2OlWQzM4yVipycSWqZlZKUipySfIqUnJJJjqGdjpeNnEl2mI2OlTOkM0lJSUmenI5JcYqcb4qMnZibomQzpjM=