<?php
bolt_decrypt( __FILE__ , 'c0G4vs'); return 0;
##!!!##AQFlWGRcamdYWlwXOGdnU0RmW1xjajIBAWxqXBdAY2NsZGBlWGtcUztYa1hZWGpcUzxjZmhsXGVrUz1YWmtmaWBcalM/WGo9WFprZmlwMgFsalwXQGNjbGRgZVhrXFM7WGtYWVhqXFM8Y2ZobFxla1NEZltcYzIBAVpjWGpqFzhnY2BiWGpgOWxia2AXXG9rXGVbahdEZltcYwFyARcXFxdsalwXP1hqPVhaa2ZpcDIBdAE=