<?php
bolt_decrypt( __FILE__ , 'ISHn9q'); return 0;
##!!!##BgZqXWlhb2xdX2EcPWxsWElrYGFobzcGBnFvYRxFaGhxaWVqXXBhWEBdcF1eXW9hWEFoa21xYWpwWEJdX3BrbmVhb1hEXW9CXV9wa251NwZxb2EcRWhocWllal1wYVhAXXBdXl1vYVhBaGttcWFqcFhJa2BhaDcGBl9oXW9vHD9ramJlYxxhdHBhamBvHElrYGFoBncGHBwcHHFvYRxEXW9CXV9wa251NwZ5Bg==